namespace FightEmpire.Core.Generation;

public static class FighterNames
{
    public static readonly Dictionary<string, string[]> FirstNames = new()
    {
        ["USA"] =
        [
            "Aaron",
            "Adam",
            "Anthony",
            "Ben",
            "Benjamin",
            "Brandon",
            "Caleb",
            "Charles",
            "Chris",
            "Christian",
            "Christopher",
            "Daniel",
            "David",
            "Dominic",
            "Eric",
            "Ethan",
            "Gabriel",
            "George",
            "Isaac",
            "Jack",
            "Jacob",
            "James",
            "Jason",
            "Joel",
            "Jonathan",
            "Jordan",
            "Joseph",
            "Julian",
            "Kevin",
            "Liam",
            "Marcus",
            "Michael",
            "Nathan",
            "Nicholas",
            "Noah",
            "Oliver",
            "Patrick",
            "Robert",
            "Samuel",
            "Thomas",
            "Tom",
            "William"
        ],

        ["Russia"] =
        [
            "Alexei",
            "Alexander",
            "Andrei",
            "Anton",
            "Artem",
            "Dmitri",
            "Evgeny",
            "Fyodor",
            "Ilya",
            "Igor",
            "Ivan",
            "Kirill",
            "Maksim",
            "Mikhail",
            "Nikita",
            "Nikolai",
            "Oleg",
            "Pavel",
            "Roman",
            "Sergei",
            "Stanislav",
            "Timur",
            "Vadim",
            "Viktor",
            "Vladimir",
            "Yaroslav"
        ],

        ["Brazil"] =
        [
            "Anderson",
            "Andre",
            "Bruno",
            "Caio",
            "Carlos",
            "Daniel",
            "Diego",
            "Eduardo",
            "Felipe",
            "Fernando",
            "Gabriel",
            "Gustavo",
            "Joao",
            "Leonardo",
            "Lucas",
            "Luiz",
            "Marcelo",
            "Marcos",
            "Mateus",
            "Matheus",
            "Miguel",
            "Paulo",
            "Pedro",
            "Rafael",
            "Renan",
            "Ricardo",
            "Rodrigo",
            "Thiago",
            "Victor",
            "Vinicius"
        ],

        ["Sweden"] =
        [
            "Adam",
            "Alexander",
            "Albin",
            "Anton",
            "Axel",
            "Benjamin",
            "Carl",
            "Daniel",
            "Elias",
            "Emil",
            "Erik",
            "Filip",
            "Fredrik",
            "Gustav",
            "Henrik",
            "Hugo",
            "Isak",
            "Jacob",
            "Jesper",
            "Johan",
            "Jonas",
            "Karl",
            "Kevin",
            "Leo",
            "Linus",
            "Lucas",
            "Marcus",
            "Martin",
            "Mattias",
            "Max",
            "Nils",
            "Oskar",
            "Samuel",
            "Simon",
            "Stefan",
            "Viktor",
            "William"
        ]
    };


    public static readonly Dictionary<string, string[]> LastNames = new()
    {
        ["USA"] =
        [
            "Adams",
            "Baker",
            "Bennett",
            "Brown",
            "Campbell",
            "Carter",
            "Clark",
            "Collins",
            "Davis",
            "Edwards",
            "Evans",
            "Foster",
            "Green",
            "Griffin",
            "Hall",
            "Harris",
            "Hill",
            "Jackson",
            "Johnson",
            "Jones",
            "Lewis",
            "Martin",
            "Miller",
            "Mitchell",
            "Morgan",
            "Morris",
            "Murphy",
            "Nelson",
            "Parker",
            "Reed",
            "Roberts",
            "Smith",
            "Taylor",
            "Thompson",
            "Walker",
            "White",
            "Williams",
            "Wilson",
            "Young"
        ],

        ["Russia"] =
        [
            "Antonov",
            "Baranov",
            "Belov",
            "Bogdanov",
            "Fedorov",
            "Gusev",
            "Ivanov",
            "Karpov",
            "Kozlov",
            "Kuznetsov",
            "Lebedev",
            "Makarov",
            "Morozov",
            "Nikolaev",
            "Orlov",
            "Pavlov",
            "Petrov",
            "Popov",
            "Romanov",
            "Semenov",
            "Sokolov",
            "Smirnov",
            "Volkov",
            "Voronin",
            "Yakovlev",
            "Zaitsev"
        ],

        ["Brazil"] =
        [
            "Almeida",
            "Alves",
            "Araujo",
            "Barbosa",
            "Carvalho",
            "Costa",
            "Fernandes",
            "Ferreira",
            "Gomes",
            "Lima",
            "Lopes",
            "Martins",
            "Mendes",
            "Moreira",
            "Nascimento",
            "Oliveira",
            "Pereira",
            "Ribeiro",
            "Rodrigues",
            "Rocha",
            "Santos",
            "Silva",
            "Soares",
            "Sousa",
            "Souza",
            "Teixeira",
            "Vieira"
        ],

        ["Sweden"] =
        [
            "Andersson",
            "Berg",
            "Bergman",
            "Carlsson",
            "Dahl",
            "Ek",
            "Eriksson",
            "Forsberg",
            "Gustafsson",
            "Hansen",
            "Hedlund",
            "Holm",
            "Johansson",
            "Jönsson",
            "Karlsson",
            "Larsson",
            "Lindberg",
            "Lindgren",
            "Lund",
            "Nilsson",
            "Nordström",
            "Olsson",
            "Persson",
            "Sandberg",
            "Sjöberg",
            "Svensson",
            "Wallin",
            "Åberg",
            "Åkesson",
            "Öberg"
        ]
    };


    public static readonly string[] Nicknames =
    {
        "The Animal",
        "The Assassin",
        "The Axe",
        "The Beast",
        "The Blackout",
        "The Blade",
        "The Boa",
        "The Bomber",
        "The Boss",
        "The Bull",
        "The Butcher",
        "The Cannon",
        "The Cobra",
        "The Crusher",
        "The Cyclone",
        "The Destroyer",
        "The Diamond",
        "The Dominator",
        "The Dragon",
        "The Eagle",
        "The Executioner",
        "The Falcon",
        "The Firestorm",
        "The Ghost",
        "The Gladiator",
        "The Hammer",
        "The Hitman",
        "The Hurricane",
        "The Hunter",
        "The Juggernaut",
        "The King",
        "The Kraken",
        "The Lion",
        "The Machine",
        "The Mauler",
        "The Mercenary",
        "The Nightmare",
        "The Outlaw",
        "The Panther",
        "The Phantom",
        "The Predator",
        "The Punisher",
        "The Reaper",
        "The Rhino",
        "The Rock",
        "The Samurai",
        "The Savage",
        "The Shark",
        "The Sniper",
        "The Soldier",
        "The Spartan",
        "The Spider",
        "The Storm",
        "The Tank",
        "The Technician",
        "The Titan",
        "The Tornado",
        "The Viking",
        "The Viper",
        "The Warrior",
        "The Wolf",
        "The Wolverine",
        "The Wrecking Ball",
        "Bad Intentions",
        "Big Trouble",
        "Black Ice",
        "Bloodhound",
        "Bonecrusher",
        "Cold Blood",
        "Dead Eye",
        "Heavy Hands",
        "Iron Fist",
        "Iron Jaw",
        "King Kong",
        "Lights Out",
        "No Mercy",
        "One Shot",
        "Pitbull",
        "Prime Time",
        "Razor",
        "Red Dragon",
        "Stone Hands",
        "Sweet Dreams",
        "Thunder",
        "War Machine",
        "Wild Card"
    };
}